"""empty message

Revision ID: 032dab0e3ab5
Revises: 63c10fc3cfb7
Create Date: 2022-08-27 20:40:35.438612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032dab0e3ab5'
down_revision = '63c10fc3cfb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'created_at')
    # ### end Alembic commands ###
