"""added approved column to patron requests/invites

Revision ID: 0baefb64f51d
Revises: 77d6043ce991
Create Date: 2022-08-18 13:42:49.003197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0baefb64f51d'
down_revision = '77d6043ce991'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patron_invites', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('patron_requests', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patron_requests', 'approved')
    op.drop_column('patron_invites', 'approved')
    # ### end Alembic commands ###
