"""empty message

Revision ID: 39cdf50fd399
Revises: 39353e84c052
Create Date: 2022-08-27 14:38:28.495658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cdf50fd399'
down_revision = '39353e84c052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
