"""empty message

Revision ID: 4c9c0eae2f77
Revises: 71fb608514d4
Create Date: 2022-08-27 22:06:28.857739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9c0eae2f77'
down_revision = '71fb608514d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
