"""trying to use pydantic

Revision ID: 549fa36a52a9
Revises: 0baefb64f51d
Create Date: 2022-08-20 03:02:41.048941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549fa36a52a9'
down_revision = '0baefb64f51d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
