"""empty message

Revision ID: 71fb608514d4
Revises: 032dab0e3ab5
Create Date: 2022-08-27 21:46:25.093104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fb608514d4'
down_revision = '032dab0e3ab5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
