"""all tables v4

Revision ID: 77d6043ce991
Revises: 835e881ad95b
Create Date: 2022-08-18 01:03:31.545369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d6043ce991'
down_revision = '835e881ad95b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(None, 'book_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'followers', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'followers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'libraries', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('patron_invites', sa.Column('inviter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'patron_invites', 'users', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patron_invites', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('patron_invites', 'librarian_id')
    op.add_column('patron_requests', sa.Column('requester_id', sa.Integer(), nullable=False))
    op.add_column('patron_requests', sa.Column('requestee_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'patron_requests', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patron_requests', 'users', ['requestee_id'], ['id'], ondelete='CASCADE')
    op.drop_column('patron_requests', 'librarian_id')
    op.drop_column('patron_requests', 'user_id')
    op.create_foreign_key(None, 'patrons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patrons', type_='foreignkey')
    op.add_column('patron_requests', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('patron_requests', sa.Column('librarian_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'patron_requests', type_='foreignkey')
    op.drop_constraint(None, 'patron_requests', type_='foreignkey')
    op.drop_column('patron_requests', 'requestee_id')
    op.drop_column('patron_requests', 'requester_id')
    op.add_column('patron_invites', sa.Column('librarian_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'patron_invites', type_='foreignkey')
    op.drop_constraint(None, 'patron_invites', type_='foreignkey')
    op.drop_column('patron_invites', 'inviter_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'libraries', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comment_votes', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'book_votes', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
