"""all tables v3

Revision ID: 835e881ad95b
Revises: b408f51d1dfd
Create Date: 2022-08-18 00:29:42.842162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835e881ad95b'
down_revision = 'b408f51d1dfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'follower_id')
    )
    op.drop_table('user_following')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_following',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name='user_following_following_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_following_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'following_id', name='user_following_pkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
