"""empty message

Revision ID: 87774c7ec982
Revises: e5fab295d44b
Create Date: 2022-08-23 23:05:05.429363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87774c7ec982'
down_revision = 'e5fab295d44b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrons',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('admin_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("admin_level IN ('librarian', 'author', 'reader')"),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'library_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patrons')
    # ### end Alembic commands ###
