"""trying to use pydantic v2

Revision ID: 96b4017375ae
Revises: 549fa36a52a9
Create Date: 2022-08-20 03:03:55.437672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b4017375ae'
down_revision = '549fa36a52a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
