"""all tables v2

Revision ID: b408f51d1dfd
Revises: 8a47dd58b2b1
Create Date: 2022-08-17 23:50:51.061017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b408f51d1dfd'
down_revision = '8a47dd58b2b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patron_invites', sa.Column('librarian_id', sa.Integer(), nullable=False))
    op.add_column('patron_invites', sa.Column('invitee_id', sa.Integer(), nullable=False))
    op.drop_constraint('patron_invites_librarian_fkey', 'patron_invites', type_='foreignkey')
    op.drop_constraint('patron_invites_invitee_fkey', 'patron_invites', type_='foreignkey')
    op.create_foreign_key(None, 'patron_invites', 'users', ['librarian_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patron_invites', 'users', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.drop_column('patron_invites', 'librarian')
    op.drop_column('patron_invites', 'invitee')
    op.add_column('patron_requests', sa.Column('librarian_id', sa.Integer(), nullable=False))
    op.drop_constraint('patron_requests_librarian_fkey', 'patron_requests', type_='foreignkey')
    op.create_foreign_key(None, 'patron_requests', 'users', ['librarian_id'], ['id'], ondelete='CASCADE')
    op.drop_column('patron_requests', 'librarian')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patron_requests', sa.Column('librarian', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'patron_requests', type_='foreignkey')
    op.create_foreign_key('patron_requests_librarian_fkey', 'patron_requests', 'users', ['librarian'], ['id'], ondelete='CASCADE')
    op.drop_column('patron_requests', 'librarian_id')
    op.add_column('patron_invites', sa.Column('invitee', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('patron_invites', sa.Column('librarian', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'patron_invites', type_='foreignkey')
    op.drop_constraint(None, 'patron_invites', type_='foreignkey')
    op.create_foreign_key('patron_invites_invitee_fkey', 'patron_invites', 'users', ['invitee'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('patron_invites_librarian_fkey', 'patron_invites', 'users', ['librarian'], ['id'], ondelete='CASCADE')
    op.drop_column('patron_invites', 'invitee_id')
    op.drop_column('patron_invites', 'librarian_id')
    # ### end Alembic commands ###
