"""empty message

Revision ID: c5216c8d1967
Revises: fccd69a99f8d
Create Date: 2022-08-22 00:35:44.844381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5216c8d1967'
down_revision = 'fccd69a99f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_votes', 'id')
    op.drop_column('comment_votes', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_votes', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('book_votes', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
