"""empty message

Revision ID: cd7d1aa150cb
Revises: 5e42a616551c
Create Date: 2022-08-25 16:56:16.165207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7d1aa150cb'
down_revision = '5e42a616551c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
