"""empty message

Revision ID: e5fab295d44b
Revises: 7f5254f4eeb9
Create Date: 2022-08-22 16:08:59.410799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fab295d44b'
down_revision = '7f5254f4eeb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'book_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'followers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'followers', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patron_invites', 'users', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patron_invites', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patron_invites', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patron_requests', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patron_requests', 'users', ['requestee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patron_requests', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patrons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patrons', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patrons', type_='foreignkey')
    op.drop_constraint(None, 'patrons', type_='foreignkey')
    op.drop_constraint(None, 'patron_requests', type_='foreignkey')
    op.drop_constraint(None, 'patron_requests', type_='foreignkey')
    op.drop_constraint(None, 'patron_requests', type_='foreignkey')
    op.drop_constraint(None, 'patron_invites', type_='foreignkey')
    op.drop_constraint(None, 'patron_invites', type_='foreignkey')
    op.drop_constraint(None, 'patron_invites', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comment_votes', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'book_votes', type_='foreignkey')
    op.drop_table('libraries')
    op.drop_table('users')
    # ### end Alembic commands ###
